# Documentation BasicAuth :
# 1. Run :
# sudo apt-get update && sudo apt-get install -y apache2-utils
# htpasswd -nbB admin 'MONPASSWORD' > auth
# 2. Create secret in Kubernetes with the content of the "auth" file generated in step 1 :
# kubectl -n staging-redis create secret generic redisinsight-basic-auth --from-file=auth

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: staging-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight:latest
          ports:
            - containerPort: 5540
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: staging-redis
spec:
  selector:
    app: redisinsight
  ports:
    - name: http
      port: 80
      targetPort: 5540

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisinsight
  namespace: staging-redis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    # Basic auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: redisinsight-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - RedisInsight"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging.redisinsight.aetherroyale.crzgames.com
      secretName: redisinsight-tls
  rules:
    - host: staging.redisinsight.aetherroyale.crzgames.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redisinsight
                port:
                  number: 80